apiVersion: apps/v1
kind: Deployment
metadata:
  name: py-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: py-app
  template:
    metadata:
      labels:
        app: py-app
    spec:
      containers:
      - name: py-app
        image: mostafag95/projecttt
        ports:
        - containerPort: 8000 
        env:
        - name: REDIS_HOST
          value: svc-redis
        - name: REDIS_PORT
          value: "6379"
                     
